version: '3'
services:
  postgres-service:
    image: postgres:16.0
    container_name: postgres-service
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: '.env'


  api-service:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev-deploy
    env_file: '.env'
    container_name: api-service
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - postgres-service
    volumes:
      - api-service-node-modules:/app/node_modules
      - ./:/app
      
volumes:
  postgres-data:
  api-service-node-modules: